### PR TITLE
Equality traits for OTA slots

### PR DESCRIPTION
**Pull request by DaneSlattery**
I would like to be able to compare slots and use this in other abstractions that require partialeq.

### CODE REVIEW

**Review by ivmarkov — CHANGES_REQUESTED** [review]
Fine, but then also put `Eq` and `Hash`.

**Comment by DaneSlattery** [comment]
I see, but the other structs in this module have if gated behind the `std` feature , such as `SlotState` for example

**Comment by ivmarkov** [comment]
> I see, but the other structs in this module have if gated behind the `std` feature , such as `SlotState` for example

That's because X years ago I myself did not realize `Hash` exists in `no_std`. These other structs need to be fixed.

**Comment by DaneSlattery** [comment]
Thank you!

**Pull request merged**
